-------------------STRING FUNCTIONS---------
select ASCII('dc')    --GIVES ASCII VALUE OF FIRST CHARACTER
select CHAR(64)     --RETURN CHARACTER FOR ASCII VALUE

---PRINTING FROM A TO Z 
DECLARE @START INT
SET @START=65
WHILE(@START<90)
BEGIN
 SELECT CHAR(@START)
SET  @START=@START+1;
END


SELECT LTRIM('   NAGARAJU')       --REMOVES WHITE SPACES ON LEFT 
SELECT RTRIM('NAGARAJU    ')      --REMOVES WHITE SPACES ON RIGHT

SELECT UPPER('nagaraju');         --CONVERTS TO UPPER CASE
SELECT LOWER('NAGARAJU')          --CONVERTS TO LOWER CASE
SELECT REVERSE('NAGARAJU');       --REVERSES GIVEN STRING
SELECT LEN('NAGARAJU  ')          --GIVES LENGTH EXCLUDING SPACES AT THE END
SELECT LEFT('NAGARAJU',4)         --GIVES SPECIFIED NO OF CHARACTERS FROM LEFT
SELECT RIGHT('NAGARAJU',5)        --GIVES SPECIFIED NO OF CHARACTERS FROM RIGHT
SELECT CHARINDEX('@','NAGARAJU@S')  --GIVES THE INDEX OF SPECIFIED CHARACTER
SELECT SUBSTRING('NAGARAJU@S',1,CHARINDEX('@','NAGARAJU@S'))  --GIVES SUBSTRING 

--QUERY TO MASK EMAIL ID 
SELECT SUBSTRING('NAGARAJUSWARNA5@GMAIL.COM',1,2)+
REPLICATE('*',LEN(LEFT('NAGARAJUSWARNA5@GMAIL.COM',CHARINDEX('@','NAGARAJUSWARNA5@GMAIL.COM')))-2)+'@'+
RIGHT('NAGARAJUSWARNA5@GMAIL.COM',LEN('NAGARAJUSWARNA5@GMAIL.COM')-CHARINDEX('@','NAGARAJUSWARNA5@GMAIL.COM'))
AS MASKED

SELECT LEN('NAGARAJU'+SPACE(5)+'SWARNA')

SELECT REPLACE('NAGARAJU SWARNA','A','@')     --REPLACES SPECIFIED PATTERN 
