--------USER DEFINED FUNCTIONS
1.SCALAR FUNCTIONS
2.INLINE TABLE VALUES FUNCTIONS
3.MULTI STATEMENT TABLE VALUED FUNCTIONS 


CREATE FUNCTION AGECALCULATOR(@DOB DATE)
RETURNS INT
AS
BEGIN
DECLARE @AGE INT
SET @AGE=DATEDIFF(YEAR,@DOB,GETDATE())-
           CASE 
             WHEN (MONTH(@DOB)>MONTH(GETDATE())) OR((MONTH(@DOB)>MONTH(GETDATE()) AND DAY(@DOB)>DAY(GETDATE())))
			 THEN 1
			 ELSE 0
			 END
RETURN @AGE
END

SELECT dbo.AGECALCULATOR('05/03/1997')              --need to specify the schema also 

DROP FUNCTION dbo.AGECALCULATOR                     --DROPPPING FNCTION 

SP_HELPTEXT AGECALCULATOR                           --GETTING FUNCTION DEF 

                                                    --TABLE VALUED FUNCTION 
--NO BEGIN AND END
alter FUNCTION UDF_FUN()
RETURNS TABLE 
AS 
RETURN (SELECT * FROM FactData)

select * from [dbo].[UDF_FUN]()

-----------------------------------MULTI STATEMENT TABLE VALUED FUNCTION 

------------DETERMINISTIC VS NON-DETERMINISTIC FUNCTIONS

SELECT RAND()
